### ISSUE TITLE
Setupの方法について、Readmeの更新提案

### ISSUE THREAD

**Issue by liruk** [ysakasin/bcdice-api#9]
はじめまして。初issueゆえ拙い部分があると思われますが、ご指摘頂けると助かります。
まとめると、Readmeの
`$ bundle exec rackup`
を
`$ bundle exec rackup -o 0.0.0.0`
に差し替える提案についてです。
--
自宅のCentos7サーバにLAN内のWindows10マシンから遠隔で配置を試みまして、Setupの最後の部分で詰まっていました。
`$ bundle exec rackup`
この通りにコマンドを入力するとLAN内外問わず接続ができない状態でした。このとき他のサービスは通常通り使えています。
調べましたところ、このようなページがヒットしました。
[sinatraでrackupからの起動でlocalhost以外からの接続を許可しようとしたらハマった件](https://suruseas.github.io/ruby/2016/11/30/sinatra-rackup-outside.html)
このページの通りに先程のコマンドを
`$ bundle exec rackup -o 0.0.0.0`
と置き換えて実行したところ、無事LAN内外問わず動作していることを確認できました。
今はサービス化まで済ませています。 
よろしくおねがいします。

**Comment by ysakasin** [comment]
提案ありがとうございます。

結論から言いますと、その方法は誤った動作を引き起こしてしまいます。BCDice-APIで想定されている方法は、**環境変数として`APP_ENV=production`を設定する**ことです。

`-o 0.0.0.0`でも一見動作するように見えますが、エラーが発生した時に詳細なエラーを発生させてしまいます。これは、sinatraが`APP_ENV`を見て動作を決定しているためです。`APP_ENV=production`にすることで、ご指摘のlocalhostしかリッスンしない問題も解決されます。BCDice-APIでも、この`APP_ENV`を見て動作を変えている点がいくつかあります。
https://github.com/sinatra/sinatra#configuration

また、READMEの表記はあくまでローカル実行用のコマンドを想定していました。実運用のコマンドがないのは不親切かなと思いますので、`docs/`に解説を追加しようと思います。

**Comment by liruk** [comment]
対応ありがとうございました！
`APP_ENV`を設定した上で更に`RACK_ENV=deployment`の方も設定する必要があり、そちらは
`$ bundle exec rackup -E deployment`
としてもよい……ということですかね。
ありがとうございました！
